# Data Exploration Techniques

In [58]:
#import SalaryGender CSV file
import pandas as pd
import numpy as np
df = pd.read_csv("SalaryGender.csv")

In [59]:
df

Salary  Gender  Age  PhD
0    140.0       1   47    1
1     30.0       0   65    1
2     35.1       0   56    0
3     30.0       1   23    0
4     80.0       0   53    1
..     ...     ...  ...  ...
95    18.6       1   26    0
96   152.0       1   56    1
97     1.8       1   28    0
98    35.0       0   44    0
99     4.0       0   24    0

[100 rows x 4 columns]

# 1.Dimensionality Check

In [60]:
df.shape

(100, 4)

In [61]:
type(df)

pandas.core.frame.DataFrame

In [62]:
df.describe()

Salary      Gender         Age         PhD
count  100.000000  100.000000  100.000000  100.000000
mean    52.524500    0.500000   46.880000    0.390000
std     42.220933    0.502519   15.271469    0.490207
min      0.250000    0.000000   20.000000    0.000000
25%     20.000000    0.000000   31.500000    0.000000
50%     39.300000    0.500000   49.000000    0.000000
75%     75.500000    1.000000   60.000000    1.000000
max    190.000000    1.000000   77.000000    1.000000

# 2.Type of Dataset

In [63]:
df['Salary'].dtype

dtype('float64')

In [64]:
df['Gender'].dtype

dtype('int64')

In [65]:
df['Age'].dtype

dtype('int64')

In [66]:
df["PhD"].dtype

dtype('int64')

# 3.Slicing and Indexing

In [67]:
List = np.array(df['Salary'])
List

array([140.  ,  30.  ,  35.1 ,  30.  ,  80.  ,  30.  ,  60.  ,  31.1 ,
       125.  ,  51.  ,   3.  ,  46.  , 150.  ,   3.  , 130.  ,  15.  ,
       130.  ,  84.  , 190.  ,  74.  ,  73.  ,  10.  ,  50.  ,   7.  ,
         9.5 ,  15.2 ,  28.6 ,  20.  ,  72.  ,  81.  , 100.  ,  90.  ,
        90.  ,  35.  ,  30.  ,  25.  ,  52.  ,   9.  ,  63.  ,  72.  ,
        16.  ,  92.  , 106.  ,   2.5 ,   9.  ,  32.  ,  32.  ,  55.  ,
        52.  ,  28.  ,  20.  ,  14.7 ,  22.3 ,  34.8 ,  84.  ,  19.  ,
       160.  ,  65.  ,  55.  ,   4.6 , 102.  ,  20.  ,  62.  ,  55.  ,
        45.6 ,  40.  ,  24.  ,  35.  ,  48.  ,  20.  ,  40.7 ,  15.  ,
         0.25, 152.  ,  39.8 ,  12.  ,  30.  , 120.  ,   1.7 ,  36.  ,
        96.  ,  38.  ,  90.  ,   9.  ,  25.8 ,  22.  ,  38.8 ,  72.  ,
        89.  ,  41.  ,  89.  ,  25.  ,  52.  , 115.  ,  66.  ,  18.6 ,
       152.  ,   1.8 ,  35.  ,   4.  ])

In [68]:
List[1:3]  #Slicing a list:

array([30. , 35.1])

In [69]:
df.iloc[:5,2:4]  #Slicing a Data frame (df) using iloc indexer:

Age  PhD
0   47    1
1   65    1
2   56    0
3   23    0
4   53    1

# 4.Identifying Unique Elements

In [70]:
df['Salary'].unique()

array([140.  ,  30.  ,  35.1 ,  80.  ,  60.  ,  31.1 , 125.  ,  51.  ,
         3.  ,  46.  , 150.  , 130.  ,  15.  ,  84.  , 190.  ,  74.  ,
        73.  ,  10.  ,  50.  ,   7.  ,   9.5 ,  15.2 ,  28.6 ,  20.  ,
        72.  ,  81.  , 100.  ,  90.  ,  35.  ,  25.  ,  52.  ,   9.  ,
        63.  ,  16.  ,  92.  , 106.  ,   2.5 ,  32.  ,  55.  ,  28.  ,
        14.7 ,  22.3 ,  34.8 ,  19.  , 160.  ,  65.  ,   4.6 , 102.  ,
        62.  ,  45.6 ,  40.  ,  24.  ,  48.  ,  40.7 ,   0.25, 152.  ,
        39.8 ,  12.  , 120.  ,   1.7 ,  36.  ,  96.  ,  38.  ,  25.8 ,
        22.  ,  38.8 ,  89.  ,  41.  , 115.  ,  66.  ,  18.6 ,   1.8 ,
         4.  ])

In [71]:
df['Gender'].unique()

array([1, 0], dtype=int64)

In [72]:
df['Age'].unique()

array([47, 65, 56, 23, 53, 27, 30, 44, 63, 22, 59, 60, 28, 25, 66, 45, 46,
       24, 36, 51, 52, 54, 26, 49, 34, 58, 77, 67, 48, 32, 43, 61, 29, 62,
       41, 57, 71, 20, 69, 37, 33, 42, 55], dtype=int64)

In [73]:
df['PhD'].unique()

array([1, 0], dtype=int64)

# 5.Value Extraction

In [77]:
df['Age'].values

array([47, 65, 56, 23, 53, 27, 53, 30, 44, 63, 22, 59, 60, 28, 65, 25, 65,
       47, 66, 45, 46, 24, 60, 63, 27, 66, 36, 30, 51, 65, 45, 52, 54, 30,
       52, 26, 49, 22, 34, 60, 28, 58, 77, 67, 27, 48, 45, 49, 36, 65, 32,
       49, 67, 22, 49, 43, 61, 43, 52, 51, 66, 29, 62, 56, 61, 56, 41, 24,
       60, 43, 57, 23, 53, 71, 20, 27, 69, 58, 37, 32, 33, 32, 60, 71, 30,
       62, 54, 42, 62, 51, 71, 29, 55, 54, 55, 26, 56, 28, 44, 24],
      dtype=int64)

# 6.Feature Mean

In [78]:
df.mean()

Salary    52.5245
Gender     0.5000
Age       46.8800
PhD        0.3900
dtype: float64

# 7.Feature Median

In [79]:
df.median()

Salary    39.3
Gender     0.5
Age       49.0
PhD        0.0
dtype: float64

# 8.Feature Mode


In [84]:
df.mode(axis=0)

Salary  Gender  Age  PhD
0    30.0       0   60  0.0
1     NaN       1   65  NaN